// todo-react-ts/src/components/item/Item.tsx
import React, { ReactNode } from "react";
import "./Item.css";
import { Item } from "../../models/Item";

interface Props extends React.Props<any> {
  item: Item;
  toggleDone: (item: Item) => void;
  delete: (item: Item) => void;
}

export class ItemComponent extends React.Component<Props> {
  public render(): ReactNode {
    return (
      <div className="item">
        <div className="item-name">{this.props.item.name}</div>
        <div className="actions">
          <button onClick={this.props.toggleDone.bind(this, this.props.item)}>
            {this.props.item.isDone ? "Undone" : "Done"}
          </button>
          <button onClick={this.props.delete.bind(this, this.props.item)}>
            Delete
          </button>
        </div>
      </div>
    );
  }
}

// todo-angular/src/app/item/item.component.ts
import { Component, Input, EventEmitter, Output } from "@angular/core";
import { ToDoItem } from "src/app/models/todo-item";

@Component({
  selector: "app-item",
  templateUrl: "./item.component.html",
  styleUrls: ["./item.component.scss"]
})
export class ItemComponent {
  @Input() item: ToDoItem;

  @Output() toggleDone = new EventEmitter<ToDoItem>();

  onToggleDone() {
    this.toggleDone.emit(this.item);
  }
}

<div class='item'>
    <div class='item-name'>
        {{item.name}}
    </div>
    <div class='actions'>
        <button (click)="onToggleDone()">{{ item.isDone ? 'Undone' : 'Done' }}</button>
        <button>Delete</button>
    </div>
</div>
