// todo-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { ToDoItem } from "src/app/models/todo-item";
import { Observable } from "rxjs";
import { ItemListService } from "src/app/services/item-list.service";
import { map } from "rxjs/operators";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent {
  constructor(private itemListService: ItemListService) {}

  private items$: Observable<ToDoItem[]> = this.itemListService.getItems();

  activeItems$ = this.items$.pipe(map(items => items.filter(item => !item.isDeleted)));
  deletedItems$ = this.items$.pipe(map(items => items.filter(item => item.isDeleted)));
  todoItems$ = this.activeItems$.pipe(map(items => items.filter(item => !item.isDone)));
  doneItems$ = this.activeItems$.pipe(map(items => items.filter(item => item.isDone)));

  onToggleDone(item){
    this.itemListService.toggleDoneItem(item);
  }

  onDelete(item){
    this.itemListService.delete(item);
  }
}

<h3>To Do</h3>

<app-list
  [items]="todoItems$ | async"
  (toggleDone)="onToggleDone($event)"
  (delete)="onDelete($event)"
>
</app-list>

<h3>Done</h3>

<app-list
  [items]="doneItems$ | async"
  (toggleDone)="onToggleDone($event)"
  (delete)="onDelete($event)"
>
</app-list>

<h4>Deleted: {{ (deletedItems$ | async).length }}</h4>

// todo-react-ts/src/components/app/App.tsx
import React from "react";
import "./App.css";
import { ListComponent } from "../list/List";
import { Item } from "../../models/Item";
import ItemListService from "../../services/item-list.service";

interface State {
  itemsToDo: Item[];
  itemsDone: Item[];
  itemsDeleted: Item[];
}

class App extends React.Component<{}, State> {
  private service = new ItemListService();
  private readonly initialItems: Item[] = [];

  state = {
    itemsToDo: this.initialItems,
    itemsDone: this.initialItems,
    itemsDeleted: this.initialItems
  }; // TODO: to find out how it works

  componentDidMount() {
    this.service.getItems().subscribe(items =>
      this.setState({
        itemsToDo: [...items.filter(item => !item.isDeleted && !item.isDone)],
        itemsDone: [...items.filter(item => !item.isDeleted && item.isDone)],
        itemsDeleted: [...items.filter(item => item.isDeleted)]
      })
    );
  }

  toggleDone = (item: Item) => {
    this.service.toggleDoneItem(item);
  };

  delete = (item: Item) => {
    this.service.delete(item);
  };

  render() {
    return (
      <div className="App">
        <h3>To Do</h3>
        <ListComponent
          items={this.state.itemsToDo}
          toggleDone={this.toggleDone}
          delete={this.delete}
        ></ListComponent>
        <h3>Done</h3>
        <ListComponent
          items={this.state.itemsDone}
          toggleDone={this.toggleDone}
          delete={this.delete}
        ></ListComponent>
        <h4>Deleted: {this.state.itemsDeleted.length}</h4>
      </div>
    );
  }
}

export default App;
